stripe_test/api/urls.py
from django.urls import path

from . import views


app_name = 'api'

urlpatterns = [
    path('buy/<int:pk>/', view=views.buy, name='buy'),
    path('success/', views.SuccessView.as_view()),
    path('cancel/', views.CancelView.as_view()),
    path('item/<int:pk>/', view=views.item, name='item'),
]

stripe_test/stripe_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls),
]

stripe_test/api/models.py
from django.db import models


class Item(models.Model):
    '''Модель Item.'''
    name = models.CharField(
        max_length = 200,
        verbose_name = 'Имя',
    )
    description = models.TextField(
        verbose_name = 'Описание',
    )
    price = models.IntegerField(
        verbose_name = 'Цена',
    )

stripe_test/api/views.py
import os
import stripe

from django.shortcuts import render, redirect, HttpResponse
from django.views.generic.base import TemplateView
from dotenv import load_dotenv

from .models import Item

load_dotenv()

stripe.api_key=os.getenv('API_KEY')

def buy(request, pk):
    item = Item.objects.get(id=pk)
    session = stripe.checkout.Session.create(
        line_items=[{
            'price_data': {
                'currency': 'usd',
                'product_data': {
                'name': item.name,
                'description': item.description
                },
            'unit_amount': item.price,
            },
            'quantity': 1,
        }],
    mode='payment',
    success_url='http://localhost:8000/success',
    cancel_url='http://localhost:8000/cancel',
    )
    return redirect(session.url, code=303)

def item(request, pk):
    item = Item.objects.get(id=pk)
    context = {
        'pk': pk,
        'name': item.name,
        'description': item.description,
        'price': item.price,
    }
    return render(request, 'item.html',context)

class SuccessView(TemplateView):
    template_name = 'success.html'


class CancelView(TemplateView):
    template_name = 'cancel.html'    

stripe_test/templates/cancel.html
<html>
  <head><title>Оплата отменена.</title></head>
  <body>
    <h1>Оплата отмененна.</h1>
  </body>
</html>

stripe_test/templates/item.html
<html>
  <head>
    <title>Buy {{ name }}</title>
  </head>
  <body>
    <h1>{{ name }}</h1>
    <p>{{ description }}</p>
    <p>{{ price }}</p>
    <form action={% url 'api:buy' pk %} method="GET">
      <button type="submit">Buy</button>
    </form>
  </body>   
</html>

stripe_test/templates/success.html
<html>
  <head><title>Спасибо за заказ!</title></head>
  <body>
    <h1>Спасибо за заказ!</h1>
  </body>
</html>